version: '3'

services:
  my-gotty:
    hostname: mygotty
    ports:
      - 8989:8080
    image: modenaf360/gotty:latest
    stdin_open: true
    tty: true
    environment:
      - GOTTY_USERNAME=myusername  # Set your actual username here
      - GOTTY_PASSWORD=mypassword  # Set your actual secure password here
