version: '3'

services:
  my-gotty:
    hostname: mygotty
    ports:
      - 8989:8080
    image: modenaf360/gotty:latest
    stdin_open: true
    tty: true
    environment:
      - GOTTY_PASSWORD=apassword  # Set your actual secure password here
